name: Docker Image CI

on:
  push:
    branches: [ relay-exit ]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64


    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: relay-exit
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/arm64 -t simeononsecurity/docker-tor-relay-exit:latest --progress=plain --push .
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simeononsecurity/docker-tor-relay-exit:latest
          
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/simeononsecurity/docker-tor-relay-exit:latest
        docker push ghcr.io/simeononsecurity/docker-tor-relay-exit:latest

